os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.2

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      gem install xcpretty -N --no-ri --no-rdoc;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      swift -version;
      xcodebuild -version;
      xcodebuild -showsdks;
      sleep 5;
      set -o pipefail;
      xcodebuild -project HelloWorld.xcodeproj -scheme HelloWorld -destination "platform=iOS Simulator,OS=10.1,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
      xcodebuild -project HelloWorld.xcodeproj -scheme Framework -destination "platform=iOS Simulator,OS=10.1,name=iPhone 7 Plus" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
